# Setup
title:               lol position classificatiom
tagline:             'Data Analysis'
description:         ''
url:                 'https://vule005.github.io'
baseurl:             '/Website-Dsc80/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name1:              Ty Albao
  name2:              Vu Le
  url:               
  email1:             
  email2:              kile@ucsd.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
